version: '3.9'

services:
  nginx:
    build:
      context: ../
      dockerfile: ./Dockerfile
    # develop:
    #   watch:
    #     - action: rebuild
    #       files:
    #         - ../**/*
    # env_file:
    #   - ./.env
    #   - ./.env.development
    #   - ./.env.local
    #   - ./.env.development.local
    networks:
      - nginx-test-network
    ports:
      - 8080:8080

networks:
  nginx-test-network:
    driver: bridge
