apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    run: nginx-server
spec:
  type: ClusterIP
  selector:
    run: nginx-server
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  sessionAffinity: None
