repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=1024"]
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: forbid-new-submodules
      - id: mixed-line-ending
  - repo: local
    hooks:
      - id: kebab-case-files-only
        name: kebab-case files only
        entry: filenames must be kebab-case only
        language: fail
        files: '[^a-z0-9.\-\/\[\]\@]'
        exclude: |
          (?x)^(
            .github/ISSUE_TEMPLATE/bug_report.md|
            .github/ISSUE_TEMPLATE/feature_request.md|
            .github/PULL_REQUEST_TEMPLATE.md|
            .github/FUNDING.yml|
            CODE_OF_CONDUCT.md|
            LICENSE|
            README.md|
            SECURITY.md|
            Dockerfile
          )$
      - id: go-fmt
        name: verify formatting
        description: Auto-format Go, and JSON files.
        entry: gofmt -l .
        types_or: [go, json, markdown]
        pass_filenames: false
        language: system
      - id: go-vet
        name: go vet
        description: Lint Go source code.
        entry: go vet
        types_or: [go, json, markdown]
        pass_filenames: false
        language: system
      - id: go-test
        name: go test
        description: Run tests using Go's built-in test runner.
        entry: go test
        types_or: [go, json]
        pass_filenames: false
        language: system
