repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=1024"]
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: forbid-new-submodules
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/crate-ci/typos
    rev: v1.16.22
    hooks:
      - id: typos
        verbose: true
        args: [
        ]
        exclude: |
          (?x)^(
            go.mod
          )$
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.55.2
    hooks:
      - id: golangci-lint
  - repo: local
    hooks:
      - id: kebab-case-files-only
        name: kebab-case files only
        entry: filenames must be kebab-case only
        language: fail
        files: '(?!\_test\.go$)[^a-z0-9.\/\[\]@-]'
        exclude: |
          (?x)^(
            .github/ISSUE_TEMPLATE/bug_report.md|
            .github/ISSUE_TEMPLATE/feature_request.md|
            .github/PULL_REQUEST_TEMPLATE.md|
            .github/FUNDING.yml|
            CODE_OF_CONDUCT.md|
            CODEOWNERS|
            Dockerfile|
            LICENSE|
            Makefile|
            README.md|
            SECURITY.md
          )$
      - id: go-test
        name: go test
        description: Run tests using Go's built-in test runner.
        entry: go test -v --coverpkg=./... ./...
        types_or: [go, json]
        pass_filenames: false
        language: system
